//
var IssueHook_1 = {
  request: {
    method: 'POST',
    url: '/githook',
    header: {
      'content-type': 'application/json',
      'user-agent': 'GitLab/13.12.1',
      'x-gitlab-event': 'Issue Hook',
      connection: 'close',
      host: '10.252.212.20:1991',
      'content-length': '2381',
    },
  },
  response: {
    status: 404,
    message: 'Not Found',
  },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/githook',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>',
};
var IssueHook_2 = {
  object_kind: 'issue',
  event_type: 'issue',
  user: {
    id: 16805,
    name: '冯劲',
    username: 'fengjin02',
    avatar_url:
      'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
    email: 'fengjin02@58.com',
  },
  project: {
    id: 71618,
    name: 'search',
    description: '一个项目依赖分析工具',
    web_url: 'https://igit.58corp.com/fengjin02/search',
    avatar_url: null,
    git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
    namespace: 'fengjin02',
    visibility_level: 20,
    path_with_namespace: 'fengjin02/search',
    default_branch: 'master',
    ci_config_path: '',
    homepage: 'https://igit.58corp.com/fengjin02/search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    http_url: 'https://igit.58corp.com/fengjin02/search.git',
  },
  object_attributes: {
    author_id: 16805,
    closed_at: null,
    confidential: false,
    created_at: '2022-04-15 14:16:56 +0800',
    description: '的点点滴滴',
    discussion_locked: null,
    due_date: null,
    id: 1500851,
    iid: 1,
    last_edited_at: null,
    last_edited_by_id: null,
    milestone_id: null,
    moved_to_id: null,
    duplicated_to_id: null,
    project_id: 71618,
    relative_position: null,
    state_id: 1,
    time_estimate: 0,
    title: 'heheeh',
    updated_at: '2022-04-15 14:16:56 +0800',
    updated_by_id: null,
    url: 'https://igit.58corp.com/fengjin02/search/-/issues/1',
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [16805],
    assignee_id: 16805,
    labels: [],
    state: 'opened',
    action: 'open',
  },
  labels: [],
  changes: {
    author_id: { previous: null, current: 16805 },
    created_at: { previous: null, current: '2022-04-15 14:16:56 +0800' },
    description: { previous: null, current: '的点点滴滴' },
    id: { previous: null, current: 1500851 },
    iid: { previous: null, current: 1 },
    project_id: { previous: null, current: 71618 },
    title: { previous: null, current: 'heheeh' },
    updated_at: { previous: null, current: '2022-04-15 14:16:56 +0800' },
  },
  repository: {
    name: 'search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    description: '一个项目依赖分析工具',
    homepage: 'https://igit.58corp.com/fengjin02/search',
  },
  assignees: [
    {
      id: 16805,
      name: '冯劲',
      username: 'fengjin02',
      avatar_url:
        'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
      email: 'fengjin02@58.com',
    },
  ],
};

var MergeRequest_1 = {
  request: {
    method: 'POST',
    url: '/githook',
    header: {
      'content-type': 'application/json',
      'user-agent': 'GitLab/13.12.1',
      'x-gitlab-event': 'Merge Request Hook',
      connection: 'close',
      host: '10.252.212.20:1991',
      'content-length': '3797',
    },
  },
  response: {
    status: 404,
    message: 'Not Found',
  },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/githook',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>',
};

var MergeRequest_2 = {
  object_kind: 'merge_request',
  event_type: 'merge_request',
  user: {
    id: 16805,
    name: '冯劲',
    username: 'fengjin02',
    avatar_url:
      'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
    email: 'fengjin02@58.com',
  },
  project: {
    id: 71618,
    name: 'search',
    description: '一个项目依赖分析工具',
    web_url: 'https://igit.58corp.com/fengjin02/search',
    avatar_url: null,
    git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
    namespace: 'fengjin02',
    visibility_level: 20,
    path_with_namespace: 'fengjin02/search',
    default_branch: 'master',
    ci_config_path: '',
    homepage: 'https://igit.58corp.com/fengjin02/search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    http_url: 'https://igit.58corp.com/fengjin02/search.git',
  },
  object_attributes: {
    assignee_id: 16805,
    author_id: 16805,
    created_at: '2022-04-15 14:24:47 +0800',
    description: 'Closes #1',
    head_pipeline_id: null,
    id: 1572967,
    iid: 1,
    last_edited_at: null,
    last_edited_by_id: null,
    merge_commit_sha: null,
    merge_error: null,
    merge_params: { force_remove_source_branch: true },
    merge_status: 'preparing',
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: 'test-222222',
    source_project_id: 71618,
    state_id: 1,
    target_branch: 'master',
    target_project_id: 71618,
    time_estimate: 0,
    title: 'Draft: Resolve "heheeh"',
    updated_at: '2022-04-15 14:24:47 +0800',
    updated_by_id: null,
    url: 'https://igit.58corp.com/fengjin02/search/-/merge_requests/1',
    source: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    target: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    last_commit: {
      id: 'aa74d22b8d77ae0d86cf7586e10a9efee21fe4bc',
      message: 'style: 修改版本号\n',
      title: 'style: 修改版本号',
      timestamp: '2022-04-06T11:50:17+08:00',
      url: 'https://igit.58corp.com/fengjin02/search/-/commit/aa74d22b8d77ae0d86cf7586e10a9efee21fe4bc',
      author: [Object],
    },
    work_in_progress: true,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [16805],
    state: 'opened',
    action: 'open',
  },
  labels: [],
  changes: { merge_status: { previous: 'unchecked', current: 'preparing' } },
  repository: {
    name: 'search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    description: '一个项目依赖分析工具',
    homepage: 'https://igit.58corp.com/fengjin02/search',
  },
  assignees: [
    {
      id: 16805,
      name: '冯劲',
      username: 'fengjin02',
      avatar_url:
        'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
      email: 'fengjin02@58.com',
    },
  ],
};

var push_1 = {
  request: {
    method: 'POST',
    url: '/githook',
    header: {
      'content-type': 'application/json',
      'user-agent': 'GitLab/13.12.1',
      'x-gitlab-event': 'Merge Request Hook',
      connection: 'close',
      host: '10.252.212.20:1991',
      'content-length': '3882',
    },
  },
  response: {
    status: 404,
    message: 'Not Found',
    header: {
      vary: 'Origin',
      'access-control-allow-origin': '*',
    },
  },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/githook',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>',
};
var push_2 = {
  object_kind: 'merge_request',
  event_type: 'merge_request',
  user: {
    id: 16805,
    name: '冯劲',
    username: 'fengjin02',
    avatar_url:
      'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
    email: 'fengjin02@58.com',
  },
  project: {
    id: 71618,
    name: 'search',
    description: '一个项目依赖分析工具',
    web_url: 'https://igit.58corp.com/fengjin02/search',
    avatar_url: null,
    git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
    namespace: 'fengjin02',
    visibility_level: 20,
    path_with_namespace: 'fengjin02/search',
    default_branch: 'master',
    ci_config_path: '',
    homepage: 'https://igit.58corp.com/fengjin02/search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    http_url: 'https://igit.58corp.com/fengjin02/search.git',
  },
  object_attributes: {
    assignee_id: 16805,
    author_id: 16805,
    created_at: '2022-04-15 14:24:47 +0800',
    description: 'Closes #1',
    head_pipeline_id: null,
    id: 1572967,
    iid: 1,
    last_edited_at: null,
    last_edited_by_id: null,
    merge_commit_sha: null,
    merge_error: null,
    merge_params: { force_remove_source_branch: true },
    merge_status: 'cannot_be_merged_recheck',
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: 'test-222222',
    source_project_id: 71618,
    state_id: 1,
    target_branch: 'master',
    target_project_id: 71618,
    time_estimate: 0,
    title: 'Draft: Resolve "heheeh"',
    updated_at: '2022-04-15 14:50:48 +0800',
    updated_by_id: null,
    url: 'https://igit.58corp.com/fengjin02/search/-/merge_requests/1',
    source: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    target: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    last_commit: {
      id: 'b38f8a5b2f7363d2a5ea2e72a18151a63c953679',
      message: 'style: 测试11\n',
      title: 'style: 测试11',
      timestamp: '2022-04-15T14:50:36+08:00',
      url: 'https://igit.58corp.com/fengjin02/search/-/commit/b38f8a5b2f7363d2a5ea2e72a18151a63c953679',
      author: [Object],
    },
    work_in_progress: true,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [16805],
    state: 'opened',
    action: 'update',
    oldrev: 'aa74d22b8d77ae0d86cf7586e10a9efee21fe4bc',
  },
  labels: [],
  changes: {
    updated_at: {
      previous: '2022-04-15 14:24:47 +0800',
      current: '2022-04-15 14:50:48 +0800',
    },
  },
  repository: {
    name: 'search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    description: '一个项目依赖分析工具',
    homepage: 'https://igit.58corp.com/fengjin02/search',
  },
  assignees: [
    {
      id: 16805,
      name: '冯劲',
      username: 'fengjin02',
      avatar_url:
        'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
      email: 'fengjin02@58.com',
    },
  ],
};

var 同意合并_1 = {
  request: {
    method: 'POST',
    url: '/githook',
    header: {
      'content-type': 'application/json',
      'user-agent': 'GitLab/13.12.1',
      'x-gitlab-event': 'Merge Request Hook',
      connection: 'close',
      host: '10.252.212.20:1991',
      'content-length': '4095',
    },
  },
  response: {
    status: 404,
    message: 'Not Found',
    header: {
      vary: 'Origin',
      'access-control-allow-origin': '*',
    },
  },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/githook',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>',
};
var 同意合并_2 = {
  object_kind: 'merge_request',
  event_type: 'merge_request',
  user: {
    id: 16805,
    name: '冯劲',
    username: 'fengjin02',
    avatar_url:
      'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
    email: 'fengjin02@58.com',
  },
  project: {
    id: 71618,
    name: 'search',
    description: '一个项目依赖分析工具',
    web_url: 'https://igit.58corp.com/fengjin02/search',
    avatar_url: null,
    git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
    namespace: 'fengjin02',
    visibility_level: 20,
    path_with_namespace: 'fengjin02/search',
    default_branch: 'master',
    ci_config_path: '',
    homepage: 'https://igit.58corp.com/fengjin02/search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    http_url: 'https://igit.58corp.com/fengjin02/search.git',
  },
  object_attributes: {
    assignee_id: 16805,
    author_id: 16805,
    created_at: '2022-04-15 14:24:47 +0800',
    description: 'Closes #1',
    head_pipeline_id: null,
    id: 1572967,
    iid: 1,
    last_edited_at: '2022-04-15 15:44:21 +0800',
    last_edited_by_id: 16805,
    merge_commit_sha: null,
    merge_error: null,
    merge_params: { force_remove_source_branch: true },
    merge_status: 'can_be_merged',
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: 'test-222222',
    source_project_id: 71618,
    state_id: 1,
    target_branch: 'master',
    target_project_id: 71618,
    time_estimate: 0,
    title: 'Resolve "heheeh"',
    updated_at: '2022-04-15 15:44:21 +0800',
    updated_by_id: 16805,
    url: 'https://igit.58corp.com/fengjin02/search/-/merge_requests/1',
    source: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    target: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    last_commit: {
      id: 'b38f8a5b2f7363d2a5ea2e72a18151a63c953679',
      message: 'style: 测试11\n',
      title: 'style: 测试11',
      timestamp: '2022-04-15T14:50:36+08:00',
      url: 'https://igit.58corp.com/fengjin02/search/-/commit/b38f8a5b2f7363d2a5ea2e72a18151a63c953679',
      author: [Object],
    },
    work_in_progress: false,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [16805],
    state: 'opened',
    action: 'update',
  },
  labels: [],
  changes: {
    last_edited_at: { previous: null, current: '2022-04-15 15:44:21 +0800' },
    last_edited_by_id: { previous: null, current: 16805 },
    title: {
      previous: 'Draft: Resolve "heheeh"',
      current: 'Resolve "heheeh"',
    },
    updated_at: {
      previous: '2022-04-15 14:50:48 +0800',
      current: '2022-04-15 15:44:21 +0800',
    },
    updated_by_id: { previous: null, current: 16805 },
  },
  repository: {
    name: 'search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    description: '一个项目依赖分析工具',
    homepage: 'https://igit.58corp.com/fengjin02/search',
  },
  assignees: [
    {
      id: 16805,
      name: '冯劲',
      username: 'fengjin02',
      avatar_url:
        'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
      email: 'fengjin02@58.com',
    },
  ],
};

var merged_just_now_1 = {
  request: {
    method: 'POST',
    url: '/githook',
    header: {
      'content-type': 'application/json',
      'user-agent': 'GitLab/13.12.1',
      'x-gitlab-event': 'Issue Hook',
      connection: 'close',
      host: '10.252.212.20:1991',
      'content-length': '2189',
    },
  },
  response: {
    status: 404,
    message: 'Not Found',
    header: {
      vary: 'Origin',
      'access-control-allow-origin': '*',
    },
  },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/githook',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>',
};
var merged_just_now_2 = {
  object_kind: 'issue',
  event_type: 'issue',
  user: {
    id: 16805,
    name: '冯劲',
    username: 'fengjin02',
    avatar_url:
      'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
    email: 'fengjin02@58.com',
  },
  project: {
    id: 71618,
    name: 'search',
    description: '一个项目依赖分析工具',
    web_url: 'https://igit.58corp.com/fengjin02/search',
    avatar_url: null,
    git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
    namespace: 'fengjin02',
    visibility_level: 20,
    path_with_namespace: 'fengjin02/search',
    default_branch: 'master',
    ci_config_path: '',
    homepage: 'https://igit.58corp.com/fengjin02/search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    http_url: 'https://igit.58corp.com/fengjin02/search.git',
  },
  object_attributes: {
    author_id: 16805,
    closed_at: '2022-04-15 15:50:19 +0800',
    confidential: false,
    created_at: '2022-04-15 14:16:56 +0800',
    description: '的点点滴滴',
    discussion_locked: null,
    due_date: null,
    id: 1500851,
    iid: 1,
    last_edited_at: null,
    last_edited_by_id: null,
    milestone_id: null,
    moved_to_id: null,
    duplicated_to_id: null,
    project_id: 71618,
    relative_position: 513,
    state_id: 2,
    time_estimate: 0,
    title: 'heheeh',
    updated_at: '2022-04-15 15:50:19 +0800',
    updated_by_id: null,
    url: 'https://igit.58corp.com/fengjin02/search/-/issues/1',
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [16805],
    assignee_id: 16805,
    labels: [],
    state: 'closed',
    action: 'close',
  },
  labels: [],
  changes: {
    closed_at: { previous: null, current: '2022-04-15 15:50:19 +0800' },
    state_id: { previous: 1, current: 2 },
    updated_at: {
      previous: '2022-04-15 14:24:47 +0800',
      current: '2022-04-15 15:50:19 +0800',
    },
  },
  repository: {
    name: 'search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    description: '一个项目依赖分析工具',
    homepage: 'https://igit.58corp.com/fengjin02/search',
  },
  assignees: [
    {
      id: 16805,
      name: '冯劲',
      username: 'fengjin02',
      avatar_url:
        'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
      email: 'fengjin02@58.com',
    },
  ],
};
var mentioned_in_commit_1 = {
  request: {
    method: 'POST',
    url: '/githook',
    header: {
      'content-type': 'application/json',
      'user-agent': 'GitLab/13.12.1',
      'x-gitlab-event': 'Merge Request Hook',
      connection: 'close',
      host: '10.252.212.20:1991',
      'content-length': '3913',
    },
  },
  response: {
    status: 404,
    message: 'Not Found',
    header: {
      vary: 'Origin',
      'access-control-allow-origin': '*',
    },
  },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/githook',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>',
};
var mentioned_in_commit_2 = {
  object_kind: 'merge_request',
  event_type: 'merge_request',
  user: {
    id: 16805,
    name: '冯劲',
    username: 'fengjin02',
    avatar_url:
      'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
    email: 'fengjin02@58.com',
  },
  project: {
    id: 71618,
    name: 'search',
    description: '一个项目依赖分析工具',
    web_url: 'https://igit.58corp.com/fengjin02/search',
    avatar_url: null,
    git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
    namespace: 'fengjin02',
    visibility_level: 20,
    path_with_namespace: 'fengjin02/search',
    default_branch: 'master',
    ci_config_path: '',
    homepage: 'https://igit.58corp.com/fengjin02/search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    http_url: 'https://igit.58corp.com/fengjin02/search.git',
  },
  object_attributes: {
    assignee_id: 16805,
    author_id: 16805,
    created_at: '2022-04-15 14:24:47 +0800',
    description: 'Closes #1',
    head_pipeline_id: null,
    id: 1572967,
    iid: 1,
    last_edited_at: '2022-04-15 15:44:21 +0800',
    last_edited_by_id: 16805,
    merge_commit_sha: 'cece7292e5ae7084342620af08d97747ec6f61e8',
    merge_error: null,
    merge_params: { force_remove_source_branch: true },
    merge_status: 'can_be_merged',
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: 'test-222222',
    source_project_id: 71618,
    state_id: 3,
    target_branch: 'master',
    target_project_id: 71618,
    time_estimate: 0,
    title: 'Resolve "heheeh"',
    updated_at: '2022-04-15 15:50:19 +0800',
    updated_by_id: 16805,
    url: 'https://igit.58corp.com/fengjin02/search/-/merge_requests/1',
    source: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    target: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    last_commit: {
      id: 'b38f8a5b2f7363d2a5ea2e72a18151a63c953679',
      message: 'style: 测试11\n',
      title: 'style: 测试11',
      timestamp: '2022-04-15T14:50:36+08:00',
      url: 'https://igit.58corp.com/fengjin02/search/-/commit/b38f8a5b2f7363d2a5ea2e72a18151a63c953679',
      author: [Object],
    },
    work_in_progress: false,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [16805],
    state: 'merged',
    action: 'merge',
  },
  labels: [],
  changes: {
    state_id: { previous: 4, current: 3 },
    updated_at: {
      previous: '2022-04-15 15:50:19 +0800',
      current: '2022-04-15 15:50:19 +0800',
    },
  },
  repository: {
    name: 'search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    description: '一个项目依赖分析工具',
    homepage: 'https://igit.58corp.com/fengjin02/search',
  },
  assignees: [
    {
      id: 16805,
      name: '冯劲',
      username: 'fengjin02',
      avatar_url:
        'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
      email: 'fengjin02@58.com',
    },
  ],
};

const aa = {
  object_kind: 'merge_request',
  event_type: 'merge_request',
  user: {
    id: 16805,
    name: '冯劲',
    username: 'fengjin02',
    avatar_url:
      'https://seccdn.libravatar.org/avatar/3fb2c4e08b91299f0fbbaf7eabb1a037?s=80&d=identicon',
    email: 'fengjin02@58.com',
  },
  project: {
    id: 71618,
    name: 'search',
    description: '一个项目依赖分析工具',
    web_url: 'https://igit.58corp.com/fengjin02/search',
    avatar_url: null,
    git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
    namespace: 'fengjin02',
    visibility_level: 20,
    path_with_namespace: 'fengjin02/search',
    default_branch: 'master',
    ci_config_path: '',
    homepage: 'https://igit.58corp.com/fengjin02/search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    http_url: 'https://igit.58corp.com/fengjin02/search.git',
  },
  object_attributes: {
    assignee_id: 10375,
    author_id: 10375,
    created_at: '2022-07-29 16:36:43 +0800',
    description: 'Closes #8',
    head_pipeline_id: null,
    id: 1612248,
    iid: 8,
    last_edited_at: '2022-07-29 16:40:31 +0800',
    last_edited_by_id: 10375,
    merge_commit_sha: '3214c45fef68c07466f435ced5c471721ba6091b',
    merge_error: null,
    merge_params: { force_remove_source_branch: true },
    merge_status: 'can_be_merged',
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: 'feature/wqq-test2',
    source_project_id: 71618,
    state_id: 3,
    target_branch: 'master',
    target_project_id: 71618,
    time_estimate: 0,
    title: 'Resolve "test2"',
    updated_at: '2022-07-29 17:02:09 +0800',
    updated_by_id: 16805,
    url: 'https://igit.58corp.com/fengjin02/search/-/merge_requests/8',
    source: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    target: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    last_commit: {
      id: 'bd54fcdaf082437fa0cc2c14f4e0f1b7161a082e',
      message: 'feat: test wqq\n',
      title: 'feat: test wqq',
      timestamp: '2022-07-29T16:40:08+08:00',
      url: 'https://igit.58corp.com/fengjin02/search/-/commit/bd54fcdaf082437fa0cc2c14f4e0f1b7161a082e',
      author: [Object],
    },
    work_in_progress: false,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [10375],
    state: 'merged',
    action: 'merge',
  },
  labels: [],
  changes: {
    state_id: { previous: 4, current: 3 },
    updated_at: {
      previous: '2022-07-29 17:02:09 +0800',
      current: '2022-07-29 17:02:09 +0800',
    },
  },
  repository: {
    name: 'search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    description: '一个项目依赖分析工具',
    homepage: 'https://igit.58corp.com/fengjin02/search',
  },
  assignees: [
    {
      id: 10375,
      name: '王骞骞',
      username: 'wangqianqian07',
      avatar_url:
        'https://igit.58corp.com/uploads/-/system/user/avatar/10375/avatar.png',
      email: 'wangqianqian07@58.com',
    },
  ],
};

// wangqianqian的请求，fengkang和的
const ggg = {
  object_kind: 'merge_request',
  event_type: 'merge_request',
  user: {
    id: 16556,
    name: '冯康',
    username: 'fengkang01',
    avatar_url:
      'https://seccdn.libravatar.org/avatar/b59d83a1cff53a15468125f607549151?s=80&d=identicon',
    email: 'fengkang01@58.com',
  },
  project: {
    id: 71618,
    name: 'search',
    description: '一个项目依赖分析工具',
    web_url: 'https://igit.58corp.com/fengjin02/search',
    avatar_url: null,
    git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
    namespace: 'fengjin02',
    visibility_level: 20,
    path_with_namespace: 'fengjin02/search',
    default_branch: 'master',
    ci_config_path: '',
    homepage: 'https://igit.58corp.com/fengjin02/search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
    http_url: 'https://igit.58corp.com/fengjin02/search.git',
  },
  object_attributes: {
    assignee_id: 10375,
    author_id: 10375,
    created_at: '2022-07-29 17:10:02 +0800',
    description: 'Closes #9',
    head_pipeline_id: null,
    id: 1612299,
    iid: 9,
    last_edited_at: '2022-07-29 17:11:06 +0800',
    last_edited_by_id: 10375,
    merge_commit_sha: '74ffd178162081c512f0a67d33c1e772ef1de778',
    merge_error: null,
    merge_params: { force_remove_source_branch: true },
    merge_status: 'can_be_merged',
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: 'feature/wqq-test3',
    source_project_id: 71618,
    state_id: 3,
    target_branch: 'master',
    target_project_id: 71618,
    time_estimate: 0,
    title: 'Resolve "test3"',
    updated_at: '2022-07-29 17:12:03 +0800',
    updated_by_id: 10375,
    url: 'https://igit.58corp.com/fengjin02/search/-/merge_requests/9',
    source: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    target: {
      id: 71618,
      name: 'search',
      description: '一个项目依赖分析工具',
      web_url: 'https://igit.58corp.com/fengjin02/search',
      avatar_url: null,
      git_ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      git_http_url: 'https://igit.58corp.com/fengjin02/search.git',
      namespace: 'fengjin02',
      visibility_level: 20,
      path_with_namespace: 'fengjin02/search',
      default_branch: 'master',
      ci_config_path: '',
      homepage: 'https://igit.58corp.com/fengjin02/search',
      url: 'git@igit.58corp.com:fengjin02/search.git',
      ssh_url: 'git@igit.58corp.com:fengjin02/search.git',
      http_url: 'https://igit.58corp.com/fengjin02/search.git',
    },
    last_commit: {
      id: '6bd4b4637167dab12f56289f882983a14756d7d0',
      message: 'feat: test wqq\n',
      title: 'feat: test wqq',
      timestamp: '2022-07-29T17:10:51+08:00',
      url: 'https://igit.58corp.com/fengjin02/search/-/commit/6bd4b4637167dab12f56289f882983a14756d7d0',
      author: [Object],
    },
    work_in_progress: false,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [10375],
    state: 'merged',
    action: 'merge',
  },
  labels: [],
  changes: {
    state_id: { previous: 4, current: 3 },
    updated_at: {
      previous: '2022-07-29 17:12:03 +0800',
      current: '2022-07-29 17:12:03 +0800',
    },
  },
  repository: {
    name: 'search',
    url: 'git@igit.58corp.com:fengjin02/search.git',
    description: '一个项目依赖分析工具',
    homepage: 'https://igit.58corp.com/fengjin02/search',
  },
  assignees: [
    {
      id: 10375,
      name: '王骞骞',
      username: 'wangqianqian07',
      avatar_url:
        'https://igit.58corp.com/uploads/-/system/user/avatar/10375/avatar.png',
      email: 'wangqianqian07@58.com',
    },
  ],
};
